---
title: BreakingThings
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@breakingthings.io
description: 
baseurl: 
url: breakingthings.io
enable_retina: true
permalink: title
nav_list:
  Home:
  - Home
  - "/"
  - fa-home
  About:
  - About
  - "/about"
  - fa-anchor
  Contact:
  - Contact
  - "/contact"
  - fa-plane
  Author:
  - Brandon Satrom
  - "/author/brandon"
  - fa-user
single_footer: <p>All your things are belong to us. Breaking Things &copy; 2016 <a
  href="/">latest posts</a></p>
footer_links:
  About:
  - About
  - "/about"
  Writer:
  - Brandon Satrom - 2016
  - "/about"
markdown: kramdown
